### ISSUE TITLE
Search for coins parameters

### ISSUE THREAD

**Issue by AlexeyKorkoza** [dan-da/coinparams#10]
Hello. I have a question. I have already used some parameters from your package in my project but I wish to know where I can take parameters for other coins. So, where did you find coins parameters ? It's very necessary for me. Thanks in advance.

**Comment by dan-da** [comment]
sorry i didnt see your question before.  For almost all the coins, the values were parsed directly from the coin's source code on github by an automated script..   In some cases, some manual review is necessary.  For non-bitcoin derived coins such as eth and monero the values were manually entered after reviewing online resources and/or source code.  let me know if any other q's.

**Comment by AlexeyKorkoza** [comment]
Thank you for your answer. Are you going to add new currencies in future in the repository ? I think this repository helps some people to find necessary parameters and they will be able to generate addresses for some currencies.

**Comment by dan-da** [comment]
I will accept pull requests if people provide them.
