### ISSUE TITLE
Coin parameters and Chain-swap question

### ISSUE THREAD

**Issue by maxcado** [dan-da/coinparams#11]
This is resourceful information. Thank you! However, information is not useful if the user does not know how to make use of it. You cannot swap from let's say bitcoin to litecoin or from dogdecoin to viacoin or whatever without doing some kind of transaction. I don't see that mentioned anywhere here. Perhaps, put more guides on chain-swap of these various cryptocurrencies.

**Comment by dan-da** [comment]
coinparams is intended for developers that are writing code to work with multiple cryptocurrencies, mainly altcoins that are direct clones/derivatives of bitcoin.  The information in coinparams makes it possible for developers to write a single piece of code, for example a wallet, that works with 300+ altcoins, without having to know the exact blockchain parameters for each one.

There is nothing about coinparams that is specifically related to trading/swapping between cryptocurrencies.   Coinparams *could* be used by a developer writing such an exchange, but I am unaware of any such at this time.

Maybe that answers your question....?
