### ISSUE TITLE
archives coinparams higher v0.1.6 corrupted

### ISSUE THREAD

**Issue by Telariust** [dan-da/coinparams#2]
C:\php-7.0.31\hd-wallet-derive-master>C:\php-7.0.31\php composer.phar install
............................
  - Installing dan-da/coinparams (v0.2.7): Downloading (100%)
    Failed to download dan-da/coinparams from dist: The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems): ZipArchive::extractTo(C:\php-7.0.31\hd-wallet-derive-master/vendor/composer/57a58c2d/dan-da-coinparams-abe4c2b\coins/con.json): failed to open stream: No such file or directory
    Now trying to download from source
............................
and bad finish.

At that, test in winrar5 is successful, but if really unpacking - corrupted con.json
For bypass it, edit composer.json to v0.1.6 coinparams. After success - del 0.1.6 and move 0.2.7 by hand.
...and fix case with path
1 match in C:\php-7.0.31\hd-wallet-derive-master\vendor\composer\autoload_classmap.php
       9      'CoinParams\\CoinParams' => $vendorDir . '/dan-da/coinparams/bindings/php/CoinParams.php',
1 match in C:\php-7.0.31\hd-wallet-derive-master\vendor\composer\autoload_static.php
      98          'CoinParams\\CoinParams' => __DIR__ . '/..' . '/dan-da/coinparams/bindings/php/CoinParams.php',
________________________________________________
hmm.... under Linux - arhives unpack success.
It problem is reserved filenames "CON/PRN/AUX/NUL/COM1/LPT1" on Windows only. 
con.json - bad name for win, need fix it!

**Comment by dan-da** [comment]
thx for report.  wow windows is special.  fixed in ea2951e1226f4811d071f4d2093c05054815fee7.  I made a new release tag v0.2.8.   Please verify.
