### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by dalijolijo** [dan-da/coinparams#6]
I want to use the coinparams with the latest modifications with hd-wallet-derive:
https://github.com/dan-da/hd-wallet-derive/blob/master/composer.json#L10

**Comment by dan-da** [comment]
Will do later tonight or in the am

**Comment by dan-da** [comment]
done.

https://github.com/dan-da/coinparams/releases/tag/v0.2.9

https://github.com/dan-da/hd-wallet-derive/releases/tag/v0.4.2
